# Generated by Django 5.0.3 on 2024-03-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_alter_sociallinks_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='default_user_image',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
    ]
