# Generated by Django 5.0.3 on 2024-03-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='compress_image',
            field=models.ImageField(blank=True, null=True, upload_to='post-thumbnail/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='post-thumbnail/'),
        ),
    ]
